# Generated by Django 5.0.7 on 2024-11-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='receipe_image',
        ),
    ]
